### ISSUE TITLE
Unable to run on Windows 8.1

### ISSUE THREAD

**Issue by PeterVanco** [mgth/LittleBigMouse#31]
Hi there,

I was looking forward to use your utility as I find the virtual dpi wall quite disturbing. Unfortunately, I'm not able to run the LittleBigMouse_Control.exe - the current application does lose the focus, but no window appear. No compatibility options helped.

From the event manager, I got following:

P1: LittleBigMouse_Control.exe
P2: 3.0.6430.40425
P3: 598b7033
P4: Erp.Notify
P5: 3.0.6430.40422
P6: 598b702d
P7: ad
P8: 70
P9: System.EntryPointNotFound
P10: 

Name of the wrong application: LittleBigMouse_Control.exe, version: 3.0.6430.40425, time stamp: 0x598b7033
Badge name: KERNELBASE.dll, version: 6.3.9600.18007, time stamp: 0x55c4c341
Exception code: 0xe0434352
Error range: 0x000000000000871c
Bad process identification: 0x404
Boot Application Run Time: 0x01d315b70edb2ad6
Path of the Bad Application: C: \ Program Files \ LittleBigMouse \ LittleBigMouse_Control.exe
Error module path: **C: \Windows\system32\KERNELBASE.dll**
Report ID: 4cf6c7d8-81aa-11e7-82ec-4851b784aa48
Full name of the missing package:
Identify a bug in a package application:

Application: LittleBigMouse_Control.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Windows.Markup.XamlParseException
Stack:
   at System.Windows.Markup.XamlReader.RewrapException(System.Exception, System.Xaml.IXamlLineInfo, System.Uri)
   at System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(System.Xaml.XamlReader, Boolean, System.Object, System.Xaml.Permissions.XamlAccessLevel, System.Uri)
   at System.Windows.Markup.XamlReader.LoadBaml(System.IO.Stream, System.Windows.Markup.ParserContext, System.Object, Boolean)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(System.IO.Stream, System.Windows.Markup.ParserContext)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<_ctor>b__0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at LittleBigMouse_Control.App.Main()

**Comment by mryauch** [comment]
Hello,
I'm on Windows 10 and have the exact same issue.  .NET Runtime is the source of one of the two Windows events.

**Comment by Cazadorro** [comment]
Also on windows 10, doesn't work at all, but I'm not getting explicit visual errors.  Note I also have Nvidia Graphics Card.

**Comment by mgth** [comment]
For windows 10 you should try v4. For windows 8.1, sorry, I know it will not work. Maybe I'll try to backport it. But Dpi Aware functions have changed.
