### ISSUE TITLE
Crashes on Startup

### ISSUE THREAD

**Issue by klownius** [mgth/LittleBigMouse#69]
When I start the program, I can see it in the Task Manager ... for about 15 seconds.  There is no UI and nothing comes up.  I tried installing this as administrator, and I tried running this as administrator.  I did the same for the previous version as well with the same result.  I use Windows  7 SP1., and I have a ELECOM trackball mouse.  My two monitors are a 4K 3840x2160 and 1920x1200.

Any help would be very appreciated.  Thank you!

**Comment by zhusulai** [comment]
I'm having the same issue. The program starts up then just terminates without displaying a UI.

**Comment by Psi-nz** [comment]
This may not be a Win7/8 issue. It crashes for me on Win 10 Pro

<details>
  <summary>Event log - Application</summary>
Faulting application name: LittleBigMouse_Control.exe, version: 4.1.6598.15330, time stamp: 0x5a683634
Faulting module name: KERNELBASE.dll, version: 10.0.17134.441, time stamp: 0x428de48c
Exception code: 0xe0434352
Fault offset: 0x000000000003a388
Faulting process id: 0x1e84
Faulting application start time: 0x01d497fb534d8123
Faulting application path: C:\Program Files\LittleBigMouse\LittleBigMouse_Control.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: a2b33afe-3cfa-4efa-a216-1503dcb86cac
Faulting package full name: 
Faulting package-relative application ID: `
</details>

<details>
  <summary>Event log - .NET Runtime</summary>
Application: LittleBigMouse_Control.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentNullException
   at System.Collections.Concurrent.ConcurrentDictionary`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].GetOrAdd(System.__Canon, System.Func`2<System.__Canon,System.__Canon>)
   at HLab.Notify.Notifier+<>c__DisplayClass18_0`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<Get>b__1(System.Object)
   at HLab.Notify.NotifierEntry..ctor(HLab.Notify.Notifier, HLab.Notify.NotifierProperty, System.Func`2<System.Object,System.Object>)
   at HLab.Notify.NotifierProperty.GetNewEntry(HLab.Notify.Notifier, System.Func`2<System.Object,System.Object>)
   at System.Collections.Concurrent.ConcurrentDictionary`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].GetOrAdd(System.__Canon, System.Func`2<System.__Canon,System.__Canon>)
   at HLab.Notify.Notifier.Get[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Object, System.Func`2<System.__Canon,System.__Canon>, HLab.Notify.NotifierProperty, System.Action)
   at HLab.Notify.NotifierObjectExt.Get[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](HLab.Notify.INotifierObject, System.Func`1<System.__Canon>, System.String)
   at LittleBigMouse.ScreenConfigs.Screen.<get_PhysicalRotated>b__34_0()
   at HLab.Notify.Notifier+<>c__DisplayClass18_0`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<Get>b__1(System.Object)
   at HLab.Notify.NotifierEntry..ctor(HLab.Notify.Notifier, HLab.Notify.NotifierProperty, System.Func`2<System.Object,System.Object>)
   at HLab.Notify.NotifierProperty.GetNewEntry(HLab.Notify.Notifier, System.Func`2<System.Object,System.Object>)
   at System.Collections.Concurrent.ConcurrentDictionary`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].GetOrAdd(System.__Canon, System.Func`2<System.__Canon,System.__Canon>)
   at HLab.Notify.Notifier.Get[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Object, System.Func`2<System.__Canon,System.__Canon>, HLab.Notify.NotifierProperty, System.Action)
   at HLab.Notify.NotifierObjectExt.Get[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](HLab.Notify.INotifierObject, System.Func`1<System.__Canon>, System.String)
   at LittleBigMouse.ScreenConfigs.Screen.<get_InMm>b__36_0()
   at HLab.Notify.Notifier+<>c__DisplayClass18_0`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<Get>b__1(System.Object)
   at HLab.Notify.NotifierEntry..ctor(HLab.Notify.Notifier, HLab.Notify.NotifierProperty, System.Func`2<System.Object,System.Object>)
   at HLab.Notify.NotifierProperty.GetNewEntry(HLab.Notify.Notifier, System.Func`2<System.Object,System.Object>)
   at System.Collections.Concurrent.ConcurrentDictionary`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].GetOrAdd(System.__Canon, System.Func`2<System.__Canon,System.__Canon>)
   at HLab.Notify.Notifier.Get[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Object, System.Func`2<System.__Canon,System.__Canon>, HLab.Notify.NotifierProperty, System.Action)
   at HLab.Notify.NotifierObjectExt.Get[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](HLab.Notify.INotifierObject, System.Func`1<System.__Canon>, System.String)

Exception Info: System.Reflection.TargetInvocationException
   at System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(System.Object, System.Object[], System.Object[])
   at System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
   at System.Reflection.RuntimePropertyInfo.GetValue(System.Object, System.Object[])
   at HLab.Notify.PropertyChangedBroker.Subscribe(System.String, System.ComponentModel.PropertyChangedEventHandler)
   at HLab.Notify.NotifierExt.SubscribeNotifier(System.ComponentModel.INotifyPropertyChanged, System.ComponentModel.PropertyChangedEventHandler, System.Collections.Generic.IList`1<System.String>)
   at HLab.Notify.Notifier.Subscribe(System.ComponentModel.INotifyPropertyChanged)
   at LittleBigMouse.ScreenConfigs.ScreenConfig.MonitorsOnCollectionChanged(System.Object, System.Collections.Specialized.NotifyCollectionChangedEventArgs)
   at LittleBigMouse.ScreenConfigs.ScreenConfig..ctor(HLab.Windows.Monitors.IMonitorsService)
   at LittleBigMouse.Control.Core.MainService.Register()
   at HLab.Plugin.PluginService.Register()
   at System.Windows.Application.<.ctor>b__1_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at LittleBigMouse_Control.App.Main()
</details>

**Comment by mgth** [comment]
This is because dpi scaling has changed betwin windows 8 and 10. And I did not try to keep compatibility, sorry for that.
